/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_com_poli_redes_jni_SNMPMessager */

#ifndef _Included_SNMPMessager
#define _Included_SNMPMessager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_com_poli_redes_jni_SNMPMessager
 * Method:    SendMenssage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_com_poli_redes_jni_SNMPMessager_SendMenssage
        (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
